import express from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { WebSocketServer, WebSocket } from 'ws';
import {
  GoogleGenAI,
  GenerateVideosOperation,
  LiveServerMessage,
  Modality
} from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const server = http.createServer(app);
const port = process.env.PORT || 3000;

// Body parser with large limit for media payloads
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// Helper: Gemini Client with required User-Agent
function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  return new GoogleGenAI({
    apiKey: apiKey || '',
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

function formatGeminiError(error: any, fallbackMessage: string = 'Operation failed') {
  const msg = error?.message || (typeof error === 'object' ? JSON.stringify(error) : String(error));
  const isQuota =
    msg.includes('429') ||
    msg.includes('RESOURCE_EXHAUSTED') ||
    msg.includes('quota') ||
    msg.includes('rate-limits');

  if (isQuota) {
    return {
      status: 429,
      error: 'Gemini API quota exceeded. Veo 3 video generation and paid multimodal models require an active quota or billing plan on your Gemini API key (https://ai.google.dev/gemini-api/docs/rate-limits).',
      isQuota: true,
      originalMessage: msg,
    };
  }

  return {
    status: 500,
    error: msg || fallbackMessage,
    isQuota: false,
    originalMessage: msg,
  };
}

// -------------------------------------------------------------
// 1. Lyria Music Generation (lyria-3-clip-preview / lyria-3-pro-preview)
// -------------------------------------------------------------
app.post('/api/music/generate', async (req, res) => {
  try {
    const { prompt, model = 'lyria-3-clip-preview', imageBase64, mimeType = 'image/jpeg' } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const ai = getGeminiClient();

    let contents: any = prompt;
    if (imageBase64) {
      contents = {
        parts: [
          { text: prompt },
          { inlineData: { data: imageBase64, mimeType } }
        ]
      };
    }

    const response = await ai.models.generateContentStream({
      model: model === 'lyria-3-pro-preview' ? 'lyria-3-pro-preview' : 'lyria-3-clip-preview',
      contents,
    });

    let audioBase64 = '';
    let lyrics = '';
    let responseMimeType = 'audio/wav';

    for await (const chunk of response) {
      const parts = chunk.candidates?.[0]?.content?.parts;
      if (!parts) continue;
      for (const part of parts) {
        if (part.inlineData?.data) {
          if (!audioBase64 && part.inlineData.mimeType) {
            responseMimeType = part.inlineData.mimeType;
          }
          audioBase64 += part.inlineData.data;
        }
        if (part.text && !lyrics) {
          lyrics = part.text;
        }
      }
    }

    if (!audioBase64) {
      return res.status(500).json({ error: 'No audio generated by the model' });
    }

    res.json({
      audioBase64,
      mimeType: responseMimeType,
      lyrics,
      model,
    });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Music generation failed');
    console.error('Music generation error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 2. Image Creation & Editing (gemini-3.1-flash-image-preview)
// -------------------------------------------------------------
app.post('/api/images/generate', async (req, res) => {
  try {
    const {
      prompt,
      aspectRatio = '16:9',
      imageSize = '1K',
      baseImageBase64,
      baseImageMimeType = 'image/png'
    } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const ai = getGeminiClient();

    let parts: any[] = [];
    if (baseImageBase64) {
      // Editing existing image
      parts.push({
        inlineData: {
          data: baseImageBase64,
          mimeType: baseImageMimeType
        }
      });
      parts.push({ text: prompt });
    } else {
      // New image generation
      parts.push({ text: prompt });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any,
          imageSize: imageSize as any,
        }
      }
    });

    let imageUrl = '';
    let textDescription = '';

    const candidateParts = response.candidates?.[0]?.content?.parts || [];
    for (const part of candidateParts) {
      if (part.inlineData?.data) {
        const mime = part.inlineData.mimeType || 'image/png';
        imageUrl = `data:${mime};base64,${part.inlineData.data}`;
      } else if (part.text) {
        textDescription += part.text;
      }
    }

    if (!imageUrl) {
      return res.status(500).json({ error: 'Model did not return an image', text: textDescription });
    }

    res.json({ imageUrl, textDescription });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Image generation failed');
    console.error('Image generation/edit error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 3. Search Grounding with Google Search (gemini-3.5-flash)
// -------------------------------------------------------------
app.post('/api/search/grounding', async (req, res) => {
  try {
    const { query } = req.body;
    if (!query) {
      return res.status(400).json({ error: 'Query is required' });
    }

    const ai = getGeminiClient();

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: `You are an illuminated literary curator and horology historian for Mythos & Quill. Research and provide a deeply informative, grounded answer to: "${query}". Include fascinating historical, mechanical, or philosophical details.`,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });

    const text = response.text || '';
    const groundingMetadata = response.candidates?.[0]?.groundingMetadata || null;

    res.json({
      text,
      groundingMetadata,
    });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Search grounding failed');
    console.error('Search grounding error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 4. Video Generation & Image-to-Video with Veo (veo-3.1-fast-generate-preview)
// -------------------------------------------------------------
app.post('/api/video/generate', async (req, res) => {
  try {
    const { prompt, aspectRatio = '16:9', imageBase64, imageMimeType = 'image/png' } = req.body;
    const ai = getGeminiClient();

    const validAspectRatio = aspectRatio === '9:16' ? '9:16' : '16:9';

    let operation;
    if (imageBase64) {
      // Image to video
      operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt || 'Animate this literary illustration into a gentle cinematic scene with subtle wind and glowing embers',
        image: {
          imageBytes: imageBase64,
          mimeType: imageMimeType,
        },
        config: {
          numberOfVideos: 1,
          resolution: '720p',
          aspectRatio: validAspectRatio,
        },
      });
    } else {
      // Text to video
      if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required for text-to-video' });
      }
      operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt,
        config: {
          numberOfVideos: 1,
          resolution: '720p',
          aspectRatio: validAspectRatio,
        },
      });
    }

    res.json({ operationName: operation.name });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Failed to start video generation');
    console.error('Veo video generate error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

app.post('/api/video/status', async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: 'operationName is required' });
    }

    const ai = getGeminiClient();
    const op = new GenerateVideosOperation();
    op.name = operationName;

    const updated = await ai.operations.getVideosOperation({ operation: op });
    res.json({
      done: updated.done || false,
      error: updated.error || null,
    });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Failed to poll video status');
    console.error('Veo video status error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

app.post('/api/video/download', async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: 'operationName is required' });
    }

    const ai = getGeminiClient();
    const op = new GenerateVideosOperation();
    op.name = operationName;

    const updated = await ai.operations.getVideosOperation({ operation: op });
    const uri = updated.response?.generatedVideos?.[0]?.video?.uri;

    if (!uri) {
      return res.status(404).json({ error: 'Video URI not found or generation failed' });
    }

    const apiKey = process.env.GEMINI_API_KEY || '';
    const videoRes = await fetch(uri, {
      headers: { 'x-goog-api-key': apiKey },
    });

    if (!videoRes.ok) {
      return res.status(videoRes.status).json({ error: 'Failed to download video file' });
    }

    res.setHeader('Content-Type', 'video/mp4');
    const arrayBuffer = await videoRes.arrayBuffer();
    res.send(Buffer.from(arrayBuffer));
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Failed to download video');
    console.error('Veo video download error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 5. Audio Transcription (gemini-3.5-transcribe)
// -------------------------------------------------------------
app.post('/api/audio/transcribe', async (req, res) => {
  try {
    const { audioBase64, mimeType = 'audio/webm' } = req.body;
    if (!audioBase64) {
      return res.status(400).json({ error: 'audioBase64 is required' });
    }

    const ai = getGeminiClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-transcribe',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType,
              data: audioBase64,
            },
          },
          { text: 'Please transcribe the speech in this audio clearly and verbatim.' },
        ],
      },
    });

    res.json({ text: response.text || '' });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Audio transcription failed');
    console.error('Audio transcription error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 6. Gemini Multi-Turn Chatbot (gemini-3.1-pro-preview / gemini-3.5-flash / gemini-3.1-flash-lite)
// -------------------------------------------------------------
app.post('/api/chat', async (req, res) => {
  try {
    const {
      messages = [],
      role = 'mentor',
      model = 'gemini-3.5-flash',
    } = req.body;

    let systemInstruction = '';
    switch (role) {
      case 'master_tobias':
        systemInstruction = `You are Master Tobias, the patient elderly horologist from "The Clockmaker of Whispering Pines". You speak in warm, gentle, contemplative prose. You relate every question to clockwork, craftsmanship, holding one's breath, and finding forgiveness in lost seconds. Never break character.`;
        break;
      case 'elena_vance':
        systemInstruction = `You are Elena Vance, the celebrated author and philosopher behind Mythos & Quill. You explain narrative structure, pedagogical themes for middle graders, why perfectionism binds children, and how to craft moral fables. Speak thoughtfully and encourage storytelling craft.`;
        break;
      case 'literary_scholar':
        systemInstruction = `You are an erudite literature professor and moral philosopher analyzing allegorical parables, historical motifs of time and mortality, and pedagogical storytelling methods. You provide deep, analytical, yet warmly inspiring reflections.`;
        break;
      default:
        systemInstruction = `You are the Socratic Story Mentor of Mythos & Quill. You help readers, educators, and seekers explore deep themes, answer philosophical sparks, and discover moral growth through thoughtful guided dialogue.`;
        break;
    }

    // Model selection validation
    let selectedModel = 'gemini-3.5-flash';
    if (model === 'gemini-3.1-pro-preview') {
      selectedModel = 'gemini-3.1-pro-preview';
    } else if (model === 'gemini-3.1-flash-lite') {
      selectedModel = 'gemini-3.1-flash-lite';
    }

    const ai = getGeminiClient();

    // Map messages format
    const formattedContents = messages.map((m: any) => ({
      role: m.sender === 'user' ? 'user' : 'model',
      parts: [{ text: m.text }],
    }));

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: formattedContents,
      config: {
        systemInstruction,
      },
    });

    res.json({
      text: response.text || '',
      modelUsed: selectedModel,
    });
  } catch (error: any) {
    const formatted = formatGeminiError(error, 'Chat generation failed');
    console.error('Chat error:', formatted.error);
    res.status(formatted.status).json(formatted);
  }
});

// -------------------------------------------------------------
// 7. Live API Real-Time Voice Conversation (gemini-3.8-live)
// -------------------------------------------------------------
const wss = new WebSocketServer({ noServer: true });

wss.on('connection', async (clientWs: WebSocket) => {
  let liveSession: any = null;

  try {
    const ai = getGeminiClient();

    liveSession = await ai.live.connect({
      model: 'gemini-3.8-live',
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } },
        },
        systemInstruction: `You are Master Tobias, the clockmaker of Whispering Pines. You are having a live voice conversation with the reader. Speak in a quiet, wise, measured cadence. Offer comforting, timeless horological wisdom about patience, breath, and forgiveness. Keep your spoken responses concise and natural.`,
      },
      callbacks: {
        onmessage: (message: LiveServerMessage) => {
          const audio = message.serverContent?.modelTurn?.parts?.[0]?.inlineData?.data;
          if (audio && clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({ audio }));
          }
          if (message.serverContent?.interrupted && clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({ interrupted: true }));
          }
        },
        onclose: () => {
          if (clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({ closed: true }));
          }
        },
      },
    });

    clientWs.on('message', (data) => {
      try {
        const parsed = JSON.parse(data.toString());
        if (parsed.audio && liveSession) {
          liveSession.sendRealtimeInput({
            audio: { data: parsed.audio, mimeType: 'audio/pcm;rate=16000' },
          });
        }
      } catch (err) {
        console.error('Error sending audio to Live session:', err);
      }
    });

    clientWs.on('close', () => {
      try {
        if (liveSession && typeof liveSession.close === 'function') {
          liveSession.close();
        }
      } catch {
        // ignore close error
      }
    });
  } catch (err: any) {
    console.error('Live connect error:', err);
    if (clientWs.readyState === WebSocket.OPEN) {
      clientWs.send(JSON.stringify({ error: err?.message || 'Live connection failed' }));
      clientWs.close();
    }
  }
});

server.on('upgrade', (request, socket, head) => {
  const pathname = new URL(request.url || '', `http://${request.headers.host}`).pathname;
  if (pathname === '/api/live') {
    wss.handleUpgrade(request, socket, head, (ws) => {
      wss.emit('connection', ws, request);
    });
  } else {
    socket.destroy();
  }
});

// -------------------------------------------------------------
// Vite Middleware / Static Serving Setup
// -------------------------------------------------------------
async function setupVite() {
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
  }

  server.listen(port, () => {
    console.log(`Mythos & Quill Atelier server running on http://localhost:${port}`);
  });
}

setupVite().catch((err) => {
  console.error('Server startup error:', err);
});
